const contact = <a href="mailto:artem.sysoev64@outlook.com">artem.sysoev64@outlook.com</a>;

export function LegalPage({ privacy = false }: { privacy?: boolean }) {
  return <main className="alerts-page legal-page">
    <nav aria-label="Navigation"><a href="/">← Accueil</a><a href="/app">Ouvrir la carte</a></nav>
    <h1>{privacy ? 'Politique de confidentialité' : 'Mentions légales'}</h1>
    {privacy ? <>
      <section><h2>Responsable du traitement</h2><p>Le responsable des traitements et ses coordonnées figurent dans les <a href="/mentions-legales#editeur">mentions légales</a>.</p></section>
      <section><h2>Quelles données sont utilisées ?</h2><p>La consultation de la carte ne nécessite pas de fournir votre email. Votre adresse email est la seule coordonnée de contact demandée pour les abonnements et l’accès à vos alertes. Aucun nom ni numéro de téléphone ne vous est demandé.</p>
        <ul><li><strong>Abonnements :</strong> email, état de confirmation, carburants et stations suivis, seuils de prix, jours d’envoi, zone choisie sur la carte, rayon et station favorite.</li><li><strong>Notifications :</strong> identifiant et adresse technique de l’abonnement push, clés nécessaires à l’envoi, libellé de l’appareil, informations du navigateur et dates d’activité. Les envois et leur état sont enregistrés.</li><li><strong>Contributions :</strong> identifiant aléatoire du navigateur, stations concernées, signalements de file d’attente, confirmations, propositions de prix ou de disponibilité et leurs dates. Cet identifiant ne contient pas votre email.</li><li><strong>Connexion et protection du service :</strong> jetons de connexion stockés sous forme d’empreintes et compteurs de limitation des demandes, notamment à partir d’une empreinte de l’adresse IP.</li></ul>
      </section>
      <section><h2>Pourquoi ces données ?</h2><p>Elles permettent de fournir les fonctions que vous demandez : connexion, digest, alertes et contributions. Les abonnements email et l’activation des notifications reposent sur votre choix et peuvent être désactivés. Les données de sécurité servent à protéger le service contre les abus, au titre de l’intérêt légitime de son éditeur. Les autres données fonctionnelles sont nécessaires à l’exécution du service demandé.</p></section>
      <section><h2>Stockage dans votre navigateur</h2><p>Un cookie de session permet de rester connecté à l’espace d’alertes pendant au maximum 90 jours. Le stockage local conserve l’identifiant aléatoire utilisé pour vos contributions et l’identifiant de votre appareil pour les notifications. Vous pouvez les effacer dans les réglages du navigateur ; cela ne supprime pas automatiquement les données déjà enregistrées sur le serveur.</p></section>
      <section><h2>Services techniques et destinataires</h2><p>Les données utiles au fonctionnement sont accessibles à l’éditeur et aux prestataires techniques concernés. Resend assure l’envoi des emails. Les notifications transitent par le service push de votre navigateur. Le fond de carte est fourni par OpenFreeMap : le chargement de ses ressources entraîne des connexions à ses serveurs, avec les informations techniques habituelles d’une requête web, dont l’adresse IP.</p><p>Ces prestataires appliquent leurs propres conditions de traitement. Consultez les informations de <a href="https://resend.com/legal/privacy-policy">Resend</a> et d’<a href="https://openfreemap.org/privacy/">OpenFreeMap</a>, ainsi que celles du fournisseur de votre navigateur.</p></section>
      <section><h2>Durées et suppression</h2><p>Les liens de connexion aux alertes expirent après 30 minutes. Les signalements de file d’attente cessent de compter après 45 minutes ; les confirmations et propositions communautaires après 3 heures. Cette expiration met fin à leur utilisation comme données récentes, mais ne supprime pas les enregistrements.</p><p>La désactivation d’une alerte ou le désabonnement du digest arrête les envois concernés sans effacer automatiquement les données associées. Le service ne dispose actuellement pas de purge automatique générale des historiques et abonnements inactifs. Pour demander leur suppression, utilisez le <a href="/mentions-legales#editeur">contact de l’éditeur</a>.</p></section>
      <section><h2>Vos choix et vos droits</h2><p>Vous pouvez vous désabonner depuis le lien présent dans les emails et désactiver vos alertes ou appareils dans <a href="/mes-alertes">Mes alertes</a>. Vous pouvez également retirer l’autorisation de notification dans votre navigateur.</p><p>Pour exercer vos droits d’accès, de rectification, d’effacement, de limitation, d’opposition ou de portabilité, selon les conditions applicables, contactez le <a href="/mentions-legales#editeur">responsable du traitement</a>. Vous pouvez adresser une réclamation à la <a href="https://www.cnil.fr/fr/plaintes">CNIL</a>.</p></section>
    </> : <>
      <section><h2>Le service</h2><p>Trajetico est accessible gratuitement et aide à comparer les stations-service, leurs prix et la disponibilité des carburants, avec des informations complémentaires apportées par la communauté.</p></section>
      <section><h2>Sources des informations</h2><p>Les prix et la disponibilité des carburants reposent principalement sur les <a href="https://www.prix-carburants.gouv.fr/">données officielles des prix des carburants</a>, mises à jour automatiquement à intervalles réguliers. Trajetico est un projet indépendant et n’est pas un service de l’administration.</p><p>Les signalements des utilisateurs sont affichés séparément et ne remplacent pas les données officielles. Les noms et enseignes peuvent provenir du <a href="https://www.data.gouv.fr/datasets/referentiel-des-noms-et-enseignes-de-stations-service-enrichi-par-openstreetmap">référentiel Chiffrex enrichi par OpenStreetMap</a> et de corrections manuelles. Attribution : © contributeurs OpenStreetMap, traitement Chiffrex, licence ODbL. Le fond de carte est fourni par OpenFreeMap ; les attributions cartographiques figurent sur la carte.</p></section>
      <section><h2>Actualité des données</h2><p>Les informations sont indicatives et peuvent évoluer entre deux mises à jour. Un prix, une disponibilité ou une file d’attente affichés ne constituent pas une garantie de la situation sur place. Vérifiez les informations auprès de la station si nécessaire. La réception des alertes dépend notamment du réseau, du navigateur et des réglages de votre appareil.</p></section>
      <section><h2>Données personnelles</h2><p>Votre email est la seule coordonnée de contact demandée. Certaines fonctions utilisent également des préférences, des contributions et des identifiants techniques. Consultez la <a href="/privacy">politique de confidentialité</a> pour connaître les données utilisées et exercer vos droits.</p></section>
    </>}
    <footer><a href={privacy ? '/mentions-legales' : '/privacy'}>{privacy ? 'Mentions légales' : 'Politique de confidentialité'}</a></footer>
    {!privacy && <section id="editeur"><h2>Éditeur et contact</h2><p>Artem Sysoev — éditeur, responsable de la publication et du traitement des données.</p><p>Pour toute question, correction ou demande : {contact}.</p></section>}
  </main>;
}
